# Example shows using the local machine still
# Remove 'connection' and set hosts to 'remote' for a remote connection
- hosts: local
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: False
  vars:
   - docroot: /var/www/serversforhackers.com/public
  tasks:
   - name: Install Python
     apt:
       name: python
       state: installed
     #raw: test -e /usr/bin/python || (apt -qqy update && apt install -qy python-minimal)
     register: pyinstalled

   - name: Add Nginx Repository
     apt_repository:
       repo: deb http://ppa.launchpad.net/nginx/stable/ubuntu xenial main
       state: present
     register: ppastable

   - name: Install Nginx
     apt:
       pkg: nginx
       state: installed
       update_cache: true
       allow_unauthenticated: yes
     when: ppastable|success and pyinstalled|success
     notify:
      - Start Nginx

   - name: Create Web Root
     file:
      path: '{{ docroot }}'
      mode: 775
      state: directory
      owner: www-data
      group: www-data
     notify:
      - Reload Nginx

  handlers:
   - name: Start Nginx
     service:
       name: nginx
       state: started

   - name: Reload Nginx
     service:
       name: nginx
       state: reloaded
